version: '3.8'

services:
  api_gateway:
    build: ./ApiGateway
    ports:
      - "5000:5000"
    networks:
      - api-to-ia
    environment:
      - AI_SERVICE_HOST=http://ai_model:5001


  ai_model:
    build: ./ApiAi
    networks:
      - api-to-ia

networks:
  api-to-ia:
    driver: bridge
