version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api_gateway
    networks:
      - api-to-ia

  api_gateway:
    build: ./ApiGateway
    ports:
      - "5000:5000"
    networks:
      - api-to-ia
    environment:
      - AI_SERVICE_HOST=http://ai_model:5001

  ai_model:
    build: ./ApiAi
    networks:
      - api-to-ia

networks:
  api-to-ia:
    driver: bridge
