### Api gateway health check
GET {{host}}:5000/hc

### AI service health check
GET {{host}}:5000/hc_model

### Blur a face
POST {{host}}:5000/blur
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="sampleFile.png"
Content-Type: image/jpeg

< ./imgs/kids.jpg
--WebAppBoundary--



### Blur a face with debug parameter
POST {{host}}:5000/blur?debug=on
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="sampleFile.png"
Content-Type: image/jpeg

< ./imgs/kids.jpg
--WebAppBoundary--



### Blur all faces
POST {{host}}:5000/blur?mode=ai
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="sampleFile.png"
Content-Type: image/jpeg

< ./imgs/toddler.png
--WebAppBoundary--


### Blur all faces with debug parameter
POST {{host}}:5000/blur?mode=random&type=blur&debug=on
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="sampleFile.png"
Content-Type: image/jpeg

< ./imgs/kids.jpg
--WebAppBoundary--


# Error responses
### Blur without image
POST {{host}}:5000/blur
Content-Type: multipart/form-data; boundary=WebAppBoundary
